// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPbZYzpFnjSK099uCQL7W12GG7VWa-M8c',
    appId: '1:881914006921:web:7f1917cf3ffabb01926558',
    messagingSenderId: '881914006921',
    projectId: 'travalong-33ad7',
    authDomain: 'travalong-33ad7.firebaseapp.com',
    storageBucket: 'travalong-33ad7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfHKlwAxd04K7AVkbr7Yxpil6MfZEkC7E',
    appId: '1:881914006921:android:eda0b404d859bac9926558',
    messagingSenderId: '881914006921',
    projectId: 'travalong-33ad7',
    storageBucket: 'travalong-33ad7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCElZSFFQvmPHloI52SSM7OhA2hYLyk1N0',
    appId: '1:881914006921:ios:566adde9c1ab552b926558',
    messagingSenderId: '881914006921',
    projectId: 'travalong-33ad7',
    storageBucket: 'travalong-33ad7.appspot.com',
    iosClientId: '881914006921-2lvfq2h0l2b39umibma1db06lltv2k9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.travalong',
  );
}
